export const SIGNUP = "SIGNUP";
export const SIGNIN = "SIGNIN";
export const ISAUTHENTICATED = "ISAUTHENTICATED";
export const SIGNOUT = "SIGNOUT";

// Errors
export const ISAUTHENTICATEDERROR = "ISAUTHENTICATEDERROR";
export const CLEARERRORMESSAGE = "CLEARERRORMESSAGE";

// Locations
export const ADDLOCATION = "ADDLOCATION";
export const ADDCURRENTLOCATION = "ADDCURRENTLOCATION";
export const STARTRECORDING = "STARTRECORDING";
export const STOPRECORDING = "STOPRECORDING";
export const ADDTRACKNAME = "ADDTRACKNAME";
export const RESET = "RESET";
